In [1]:
import pandas as pd

weather = pd.read_csv("weather.csv")
waits   = pd.read_csv("disney_wait_times.csv")

In [2]:
weather.head()
waits.head()

,Land,Ride,Wait Time,Local Time,Day of Week
0,Avengers Campus,Guardians of the Galaxy - Mission: BREAKOUT!,40,2024-07-08 18:30:03.881392-07:00,Monday
1,Avengers Campus,Guardians of the Galaxy - Monsters After Dark,0,2024-07-08 18:30:03.881392-07:00,Monday
2,Avengers Campus,WEB SLINGERS: A Spider-Man Adventure,40,2024-07-08 18:30:03.881392-07:00,Monday
3,Avengers Campus,WEB SLINGERS: A Spider-Man Adventure Single Rider,0,2024-07-08 18:30:03.881392-07:00,Monday
4,Buena Vista Street,Red Car Trolley,0,2024-07-08 18:30:03.881392-07:00,Monday

In [4]:
# 1. Parse Local Time as timezone-aware datetimes in UTC
waits["Local Time"] = pd.to_datetime(
    waits["Local Time"],
    utc=True,
    errors="coerce"   # turns bad/missing values into NaT instead of breaking
)

# 2. Now it's a proper datetime64[ns, UTC] Series, so .dt works
waits["Date"] = waits["Local Time"].dt.strftime("%Y-%m-%d")

In [5]:
weather_cols_to_keep = [
    "Date",
    "tempmax", "tempmin", "temp",
    "humidity", "precip",
    "windgust", "windspeed", "winddir",
    "sealevelpressure",
    "cloudcover", "visibility",
    "solarradiation", "solarenergy",
    "uvindex", "severerisk",
    "sunrise", "sunset", "moonphase",
    "conditions", "description",
]

weather_for_merge = weather[weather_cols_to_keep]
weather_for_merge.head()

,Date,tempmax,tempmin,temp,humidity,precip,windgust,windspeed,winddir,sealevelpressure,...,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description
0,2024-07-09,83.2,66.9,72.6,77.5,0.0,19.7,10.2,214.3,1009.3,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
1,2024-07-10,81.5,65.7,72.8,77.5,0.0,17.4,10.7,203.0,1010.2,...,7.0,310.0,26.8,9.0,10.0,2024-07-10 05:49:34,2024-07-10 20:04:43,0.16,Partially cloudy,Partly cloudy throughout the day.
2,2024-07-11,85.1,66.4,72.1,81.4,0.0,18.8,9.6,204.1,1010.8,...,8.0,250.4,21.6,10.0,10.0,2024-07-11 05:50:09,2024-07-11 20:04:24,0.19,Partially cloudy,Partly cloudy throughout the day.
3,2024-07-12,77.5,65.2,70.0,82.9,0.0,23.0,10.0,211.6,1011.1,...,7.0,170.4,14.5,9.0,10.0,2024-07-12 05:50:44,2024-07-12 20:04:03,0.22,Partially cloudy,Partly cloudy throughout the day.
4,2024-07-13,84.0,66.9,71.8,75.4,0.0,24.4,11.0,207.4,1013.3,...,8.7,304.5,26.2,9.0,10.0,2024-07-13 05:51:19,2024-07-13 20:03:40,0.25,Partially cloudy,Clearing in the afternoon.

In [6]:
merged = waits.merge(
    weather_for_merge,
    on="Date",
    how="left"    # keep all wait-time rows even if some dates lack weather
)

In [7]:
final_cols = [
    "Land",
    "Ride",
    "Wait Time",
    "Local Time",
    "Day of Week",
    "Date",
    "tempmax",
    "tempmin",
    "temp",
    "humidity",
    "precip",
    "windgust",
    "windspeed",
    "winddir",
    "sealevelpressure",
    "cloudcover",
    "visibility",
    "solarradiation",
    "solarenergy",
    "uvindex",
    "severerisk",
    "sunrise",
    "sunset",
    "moonphase",
    "conditions",
    "description",
]

merged = merged[final_cols]
merged.head()

,Land,Ride,Wait Time,Local Time,Day of Week,Date,tempmax,tempmin,temp,humidity,...,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description
0,Avengers Campus,Guardians of the Galaxy - Mission: BREAKOUT!,40,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
1,Avengers Campus,Guardians of the Galaxy - Monsters After Dark,0,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
2,Avengers Campus,WEB SLINGERS: A Spider-Man Adventure,40,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
3,Avengers Campus,WEB SLINGERS: A Spider-Man Adventure Single Rider,0,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
4,Buena Vista Street,Red Car Trolley,0,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.

In [8]:
# Make sure Wait Time is numeric (just in case it's a string)
merged["Wait Time"] = pd.to_numeric(merged["Wait Time"], errors="coerce")

# Keep only rows where Wait Time is not 0 and not NaN
merged = merged[merged["Wait Time"] != 0].dropna(subset=["Wait Time"])

merged.head()

,Land,Ride,Wait Time,Local Time,Day of Week,Date,tempmax,tempmin,temp,humidity,...,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description
0,Avengers Campus,Guardians of the Galaxy - Mission: BREAKOUT!,40,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
2,Avengers Campus,WEB SLINGERS: A Spider-Man Adventure,40,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
5,Cars Land,Luigi's Rollickin' Roadsters,20,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
6,Cars Land,Mater's Junkyard Jamboree,10,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.
7,Cars Land,Radiator Springs Racers,50,2024-07-09 01:30:03.881392+00:00,Monday,2024-07-09,83.2,66.9,72.6,77.5,...,7.9,288.9,24.8,9.0,10.0,2024-07-09 05:49:01,2024-07-09 20:05:01,0.12,Partially cloudy,Clearing in the afternoon.

In [9]:
merged.to_csv("wait_times_with_weather_clean.csv", index=False)